project:
  type: website
  output-dir: docs
execute:
  freeze: true
website:
  google-analytics: "G-XNZGT59XWP"
  title: "Isaac Flath"
  favicon: favicon/favicon-32x32.png
  margin-header: subscribe.html
  open-graph:
    locale: en_US
  twitter-card:
    image: street.jpg
    card-style: summary
    creator: "@isaac_flath"
  site-url: https://isaac-flath.tech/
  description: "Blog for machine learning, programming, computer science and other data science related topics"
  navbar:
    right:
      - text: "About Me"
        file: index.qmd
      - text: "Blog"
        file: blog.qmd
      - text: "TIL"
        file: til.qmd
      - text: "Consulting"
        file: consulting.qmd
      - text: "Testimonials"
        file: testimonials.ipynb
  page-footer: 
    left: "Isaac Flath" 
    right: 
      - icon: linkedin
        text: LinkedIn
        href: https://linkedin.com/in/isaacflath/
      - icon: github
        text: Github
        href: https://github.com/isaac-flath
      - icon: twitter
        text: Twitter
        href: https://twitter.com/isaac_flath
      - icon: mastodon
        text: Mastodon
        href: https://sigmoid.social/web/@isaac_flath
      - icon: rss
        text: Blog RSS
        href: blog.xml
      - icon: rss
        text: TIL RSS
        href: til.xml
format:
  html:
    theme: cosmo
    css: styles.css


